### ISSUE TITLE
Improve SDK packaging

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-ios-sdk#218]
Checkout cocoa pods. Might worth taking a look at Respoke SDKs, seems that they have been doing a good job of it.

**Comment by gizmoboy7** [comment]
Bump, are you guys planning to add cocoapods to the restcomm library?

**Comment by atsakiridis** [comment]
Yes, that is the plan, but right now there's very little availability :( 

Would you be interested to take a shot at it and contribute it back to the project? We'll be there to guide you with anything you need, of course ;)

**Comment by atsakiridis** [comment]
@giridharvc7 we have introduced CocoaPods for the SDK. You can check http://documentation.telestax.com/connect/sdks/restcomm-client-ios-sdk-quick-start.html on how to use that. Closing this issue
