### ISSUE TITLE
Add support for h.264

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-ios-sdk#310]
To get better performance

**Comment by deruelle** [comment]
Given that Google Chrome doesn't implement H264 yet. I would think of postponing that to post 1.0.0.GA release.

**Comment by atsakiridis** [comment]
Sure, added it for 2.0.0 BETA

**Comment by atsakiridis** [comment]
@deruelle seems H264 was added in chrome 52 (which is stable for a couple of weeks). So I guess it would be a good idea to check this earlier. Adding it as BETA5 content, to see if the iOS build of webrtc supports it.

**Comment by atsakiridis** [comment]
Verified with Chrome 54 and is working fine. Notice that with previous Chrome versions there are issues with calls between iOS and Web
