### ISSUE TITLE
Consider simplifying SDP handling and video/audio selection

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-ios-sdk#311]
After working with the webrtcomm code I realized that we are adding some manual steps for creating the full SDP that are probably not needed. Seems that after candidates gathering is complete the full SDP can be directly retrieved from PeerConnection.localDescription, instead of constructing it manually from bare SDP + candidates as provided by respective PeerConnection callbacks.

Another thing we can do is to consider following the new logic for video/audio selection as we did for webrtcomm. That is when an audio only call is made or answered we should initialize PeerConnection without video in local MediaStream. Right now we are only setting offerToReceiveVideo to false which probably gets us half way through. 

@deruelle, what do you think, should I add this for next release?

**Comment by deruelle** [comment]
1. When we support trickle ICE, constructing it manually from bare SDP + candidates will be needed I think as we will need to update the other end for each candidate found to speed up the call setup time. So I would suggest keeping the code around for that in light of this. However at the moment you can go with waiting that the candidates gathering is done as you suggest as we don't support Trickle ICE

2. That makes sense to me.
