### ISSUE TITLE
Support tel-uri as well as custom URI scheme for foreign App to leverage Olympus telecom facilities

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-ios-sdk#313]
And maybe add 'client:' 

As part of this activity also check how we could invoke our SDK from another App that wants to make a call.

Useful links:
* https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html
* https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/Introduction/Introduction.html#//apple_ref/doc/uid/TP40007899
* http://iosdevelopertips.com/cocoa/launching-your-own-application-via-a-custom-url-scheme.html

**Comment by atsakiridis** [comment]
For iOS you can invoke an App (for example Messenger) from another App using a custom URL scheme. So we could probably define custom URLs for 'sip:' and 'tel:' for example which don't seem reserved by Apple (keep in mind that -quoting Apple- 'If your URL type includes a scheme that is identical to one defined by Apple, the Apple-provided app is launched instead of your app'). 

The problem is -again quoting Apple- 'If more than one third-party app registers to handle the same URL scheme, there is currently no process for determining which app will be given that scheme'. So maybe the best approach is to use a URL relevant to restcomm to avoid clashes.

For example we could define 3 different URIs:

- restcomm-tel:+30210XXXXXXX (tel-uri)
- restcomm-sip:bob@telestax.com (use sip:)
- restcomm-client:bob (use client:)

@ivelin, @deruelle, @gvagenas: thoughts?

**Comment by deruelle** [comment]
using a namespace as you describe is the right way to go so it doesn't collide with other application. At the same time we should also register tel, sip and client so that if the user doesn't have any application to handle that, by default Olympus will be used to place calls.
I would say BETA4 if not too complex to implement

**Comment by atsakiridis** [comment]
Since Restcomm doesn't support tel-uri yet (https://github.com/RestComm/Restcomm-Connect/issues/509), convert tel: to sip: for calls in the SDK level as discussed with @gvagenas.
