### ISSUE TITLE
Further improve debugging SDK using Olympus App

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-ios-sdk#352]
Although https://github.com/RestComm/restcomm-ios-sdk/issues/345 was a big help a big issue is that due to the fact that project files are still separate, introducing a new source file in 'debug' project, doesn't automatically make it show up in regular project. And such issues are hard to debug as you don't see an apparent reason for failure. 

Need to consider our options at some point

**Comment by atsakiridis** [comment]
After a couple of months use with #345 , this does not seem such an improvement afterall. The fact that project files need to be updated makes this a mess. At least with the previous state we new a set of specific steps to go from one debug to non-debug and vice-versa.

Maybe it would be a good idea to somehow generate non-debug from debug when we want. Let's consider it and reach a conclusion

For now I'm reverting #345 until we can better think this through

**Comment by ipsilantide** [comment]
@atsakiridis test

**Comment by ipsilantide** [comment]
@atsakiridis test2

**Comment by ipsilantide** [comment]
@atsakiridis test3

**Comment by ipsilantide** [comment]
@atsakiridis test4
