### ISSUE TITLE
Integrate latest Webrtc library

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-ios-sdk#397]
I started working on that for BETA4 in order to see if it helps with https://github.com/RestComm/restcomm-ios-sdk/issues/374, but turns out that it's not trivial to do that. Code so far at branch atsakiridis_issue397

Some notes for when we resume this activity:
- Seems the API has changed in some respects in Webrtc library because I'm getting unresolved symbols for some symbols that are supposed to be there in the Webrtc library:

```
Undefined symbols for architecture armv7:
  "_utf8_nextCharSafeBody", referenced from:
      _validate_dispatch_data_partial_string in libWebRTC-12607-ios-armeabi_v7a-Debug.a(socketrocket.SRWebSocket.o)
  "_OBJC_CLASS_$_RTCICECandidate", referenced from:
      objc-class-ref in libRestCommClient.a(MediaWebRTC.o)
  "_OBJC_CLASS_$_RTCVideoCapturer", referenced from:
      objc-class-ref in libRestCommClient.a(MediaWebRTC.o)
  "_OBJC_CLASS_$_RTCPair", referenced from:
      objc-class-ref in libRestCommClient.a(MediaWebRTC.o)
  "_OBJC_CLASS_$_RTCICEServer", referenced from:
      objc-class-ref in libRestCommClient.a(MediaWebRTC.o)
      objc-class-ref in libRestCommClient.a(ARDCEODTURNClient.o)
      objc-class-ref in libRestCommClient.a(RTCICEServer+JSON.o)
      l_OBJC_$_CATEGORY_RTCICEServer_$_JSON in libRestCommClient.a(RTCICEServer+JSON.o)
ld: symbol(s) not found for architecture armv7
```
- I found out that in the generated library there is RTCIceCandidate and after some digging I discovered a seemingly new location for public headers inside the webrtc source tree: webrtc/sdk/objc/Framework/Headers/WebRTC (instead of talk/app/webrtc/objc/public). I asked about that in discuss-webrtc with title [Public headers for Webrtc library for iOS, framework, podspec](https://groups.google.com/forum/#!searchin/discuss-webrtc/Public$20headers$20for$20Webrtc$20library$20for$20iOS$2C$20framework$2C$20podspec/discuss-webrtc/Pt3gKgi56J8/hfamq58vOAAJ) and still wait for answer.
- Pointing the headers search path towards that new location I found numerous issues that I started to fix, but I hit a wall with RTCSessionDescriptionDelegate protocol and:

```
- (void)peerConnection:(RTCPeerConnection *)peerConnection
    didCreateSessionDescription:(RTCSessionDescription *)sdp
                          error:(NSError *)error
```

Seems that this protocol is no longer existing in the 'new' headers. To make things even more complicated the latest AppRTCDemo App seems to still be using this protocol somehow, even though it seems to have adapted its header files to the new logic.

**Comment by shantanu123** [comment]
Anybody can please help me, I am also facing the same issue mentioned above. Getting linker error. Please see the attached screenshot and any help to resolve this linker error really appre
![screen shot 2016-05-20 at 3 14 21 pm](https://cloud.githubusercontent.com/assets/3174434/15508267/5d8cc276-21ec-11e6-8abb-13d4df610460.png)
ciated.

**Comment by atsakiridis** [comment]
This will be handled with #565. Closing
