### ISSUE TITLE
Need Runnable Code

### ISSUE THREAD

**Issue by PrithiviMelio** [RestComm/restcomm-ios-sdk#435]
Kinldy update the helloworld and olympus code.

I am not able to run the package

**Comment by atsakiridis** [comment]
@PrithiviMelio please provide more data on the issue you are having. Hello world and olympus code should work out of the box

**Comment by PrithiviMelio** [comment]
Hi Antonis,

Now i am trying to explore Screen Sharing using RestComm iOS SDK

https://github.com/RestComm/restcomm-ios-sdk <https://github.com/RestComm/restcomm-ios-sdk>

In the above link Sample folder contains two projects Hello World and Olympus. But i am not able to run the code it shows some dependencies error.

Regards,
Prithivi

**Comment by atsakiridis** [comment]
Hi @PrithiviMelio, first off Screen Sharing is not yet supported in the Restcomm iOS SDK. They are planned for a bit later down the road. But the webrtc foundation is there so it shouldn't be that hard ;). Would you be interested in contributing it?

I 'll need more information on what you are trying and what goes wrong to be able to assist on that.

**Comment by PrithiviMelio** [comment]
Hi Antonis,

Thanks for your response. I am trying to explore RestComm for building solutions that leverage video chat, screen share etc., 

I can probably start with video calls using iOS SDK. Also is the android SDK equivalent to iOS in terms of features.

Here is what I am trying to do is to run the following code to connect and enable video conferencing 

- (void)viewDidLoad
{
    [super viewDidLoad];

    self.isRegistered = NO;
    self.isInitialized = NO;

    self.parameters = [[NSMutableDictionary alloc] initWithObjectsAndKeys:
                       @"sip:ios-sdk@cloud.restcomm.com", @"aor",
                       @"+1234", @"password",
                       nil];
    
    // CHANGEME: set the IP address of your RestComm instance in the URI below
    [self.parameters setObject:@"cloud.restcomm.com" forKey:@"registrar"];

    // initialize RestComm Client by setting up an RCDevice
    self.device = [[RCDevice alloc] initWithParams:self.parameters delegate:self];

    self.connection = nil;
    
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(register:) name:UIApplicationDidBecomeActiveNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(unregister:) name:UIApplicationDidEnterBackgroundNotification object:nil];
}

// ---------- UI events
- (IBAction)dialPressed:(id)sender
{
    if (self.connection) {
        NSLog(@"Connection already ongoing");
        return;
    }

    // CHANGEME: set the number of the RestComm Application you wish to contact (currently we are using '1235',
    // which is the Hello World RestComm Application). Also set the ip address for your RestComm instance
    [self.parameters setObject:@"sip:+1235@cloud.restcomm.com" forKey:@"username"];

    // call the other party
    self.connection = [self.device connect:self.parameters delegate:self];
    
    self.callLabel.text = [NSString stringWithFormat:@"Calling %@", [self.parameters objectForKey:@"username"]];
    self.statusLabel.text = @"Initiating Call...";
}

————————

and I am getting the following error

[SipManager eventLoop] another instance already running; bailing
Jun  8 18:46:32  restcomm-helloworld[430] <Notice>: (RCDevice.m:296) [RCDevice sipManagerDidInitializedSignalling]
2016-06-08 18:46:32.023 restcomm-helloworld[430:57773] -[ViewController deviceDidInitializeSignaling:]: unrecognized selector sent to instance 0x16613ed0
2016-06-08 18:46:32.024 restcomm-helloworld[430:57773] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ViewController deviceDidInitializeSignaling:]: unrecognized selector sent to instance 0x16613ed0'
*** First throw call stack:
(0x24429b0b 0x23be6dff 0x2442f455 0x2442d0ab 0x24357298 0x39f2b9 0x383171 0x380e91 0x243d4b75 0x243eb9e7 0x243eb569 0x243e993f 0x243381c9 0x24337fbd 0x25954af9 0x28a70435 0x9eb3b 0x23fe4873)
libc++abi.dylib: terminating with uncaught exception of type NSException
 
————————

Appreciate any help

Regards,
Prithivi

**Comment by SURENDRA7700** [comment]
![screen shot 2016-07-28 at 4 46 42 pm](https://cloud.githubusercontent.com/assets/13854872/17210826/e917739e-54e2-11e6-9daa-495a73d19c44.png)

here aim eating dependencies error please provide runnable code

**Comment by atsakiridis** [comment]
Hi @PrithiviMelio, really sorry for the delayed reply. This issue you 're facing should have been fixed in latest release, also in latest release we have integrated CocoaPods, so it should be a snap to integrate with your App. For more info please check in our [Quick Start Guide](http://docs.telestax.com/restcomm-client-ios-sdk-quick-start/).

Closing issue for now, please feel free to reopen if you still have issues
