### ISSUE TITLE
[SipManager convert2FullURI], after conversion: sip:1014@esip.ccilconnect.com Aug 17 23:49:02  restcomm-helloworld[2464] <Notice>: (SipManager.mm:794) [SipManager convert2FullDomain], after conversion: sip:(null) Aug 17 23:49:02  restcomm-helloworld[2464] <Notice>: (RCDevice.m:148) [RCDevice listen], state: 1

### ISSUE THREAD

**Issue by SURENDRA7700** [RestComm/restcomm-ios-sdk#448]
Hi 

iam getting error while running please reslove isuue 
ASAP 

PLEASE ATTCH ME RUNNABLE CODE WHEN YOU ARE FREE  

![screenshot 2016-08-17 23 54 23](https://cloud.githubusercontent.com/assets/13854872/17748234/07a25ac4-64d6-11e6-9244-06527c0a91b4.png)

**Comment by atsakiridis** [comment]
Hello, I think the issue is that you are not passing key 'registrar' in [RCDevice initWithDelegate] with a valid SIP registrar, like 'esip.ccilconnect.com'. Can you retry with that?

**Comment by atsakiridis** [comment]
@SURENDRA7700 keep in mind that 'aor' needs to be of the form: 'sip:username@domain' or in simplified format 'username'

**Comment by ituaijagbone** [comment]
@atsakiridis Another reason could be [this](https://github.com/RestComm/restcomm-ios-sdk/blob/2a536f0fd6478ce896caf8c4771840edbe170e70/RestCommClient/RestCommClient/SipManager/SipManager.mm#L415) calling **UTF8String** on NULL when "signaling-certificate-dir" is not set during RCDevice initialization.

**Comment by atsakiridis** [comment]
@ituaijagbone u mean the crash? If so I don't think so since in objective-c it is allowed to call a method on a nil object (it's weird I know...). On the general issue, agreed and we have already added issues to clearly describe the problem and plan to work on them.
