### ISSUE TITLE
Regarding Hello world

### ISSUE THREAD

**Issue by SURENDRA7700** [RestComm/restcomm-ios-sdk#450]
Hi i want to imPlement SIP CALLING 

I ATTACHED SCREEN shots HERE

Please reslove issue i specified aor and password and ip still i am getting problem

please resolve this isSue ASAP

![screen shot 2016-08-18 at 2 04 49 pm](https://cloud.githubusercontent.com/assets/13854872/17767253/decf0cb0-654c-11e6-9617-34ca829e8f6f.png)
![screen shot 2016-08-18 at 2 04 56 pm](https://cloud.githubusercontent.com/assets/13854872/17767254/ded02ee2-654c-11e6-8eb9-46ed85c7c821.png)
![screen shot 2016-08-18 at 2 04 49 pm](https://cloud.githubusercontent.com/assets/13854872/17767403/7e72a29a-654d-11e6-986a-3dc9542b1dae.png)
![screen shot 2016-08-18 at 2 04 56 pm](https://cloud.githubusercontent.com/assets/13854872/17767404/7e798484-654d-11e6-9abc-e5355d95e48a.png)

**Comment by atsakiridis** [comment]
@SURENDRA7700, please avoid opening multiple issues for the same problem. Also, if you want this urgently fixed, please contact info@telestax.com so that our team can allocate time for this ASAP.

**Comment by SURENDRA7700** [comment]
Thank You for Rly me .I am now go trough coding now i am resloving one by
one thank you
