### ISSUE TITLE
Regarding olympia 

### ISSUE THREAD

**Issue by SURENDRA7700** [RestComm/restcomm-ios-sdk#451]
i entered domain username and password still getting error please resolve this issue

![screen shot 2016-08-18 at 5 19 13 pm](https://cloud.githubusercontent.com/assets/13854872/17772701/ef60de30-6567-11e6-8c23-01618426c34a.png)

**Comment by atsakiridis** [comment]
Hello @SURENDRA7700, as I said previously please put your new findings in the original issue: https://github.com/RestComm/restcomm-ios-sdk/issues/448 so that we can follow up.
