### ISSUE TITLE
RCConnection Error call timed out

### ISSUE THREAD

**Issue by SURENDRA7700** [RestComm/restcomm-ios-sdk#452]
Hi ..i am doing restcomm olympia here i integrated my credentilas i got alert as restcomm connected via wifi an d after making call i got alert as RCConnection Error call timed out

2016-08-23 15:30:31.037 restcomm-olympus[2979:1441459] [CallViewController hangUpPressed]
2016-08-23 15:30:31.037 restcomm-olympus[2979:1441459] [CallViewController stopVideoRendering]
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (RCConnection.m:129) [RCConnection disconnect]
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (RCConnection.m:158) [RCConnection disconnect] before disconnectMedia
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (MediaWebRTC.m:173) [MediaWebRTC disconnect]
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (MediaWebRTC.m:205) [MediaWebRTC disconnect] end
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (RCConnection.m:160) [RCConnection disconnect] after disconnectMedia
2016-08-23 15:30:31.399 restcomm-olympus[2979:1441459] [CallViewController hangUpPressed], dismissing
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (MediaWebRTC.m:586) [MediaWebRTC iceConnectionChanged:6]
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (MediaWebRTC.m:103) [MediaWebRTC dealloc]
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (SipManager.mm:344) [SipManager didSessionRouteChange], AudioSession change reason: 3
Aug 23 15:30:31  restcomm-olympus[2979] <Notice>: (MediaWebRTC.m:554) [MediaWebRTC signalingStateChanged:5]
send 2262 bytes to udp/[104.218.120.106]:5060 at 10:00:32.260532:

---

   INVITE sip:102@xsip.ccilconnect.com SIP/2.0
   Via: SIP/2.0/UDP 192.168.137.224:63612;rport;branch=z9hG4bKUpySD87m4eerp
   Max-Forwards: 70
   From: sip:100001@xsip.ccilconnect.com;tag=NgD6vX8N2FtDr
   To: sip:102@xsip.ccilconnect.com
   Call-ID: 4301a54a-e3bb-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637150 INVITE
   Contact: sip:175.101.6.194:62234;transport=udp
   User-Agent: TelScale Restcomm iOS Client 1.0.0 BETA4
   Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, PRACK, MESSAGE, SUBSCRIBE, NOTIFY, REFER, UPDATE
   Supported: timer, 100rel
   Content-Type: application/sdp
   Content-Length: 1683

   v=0
   o=- 2190532238883068011 2 IN IP4 127.0.0.1
   s=-
   t=0 0
   a=group:BUNDLE audio
   a=msid-semantic: WMS ARDAMS
   m=audio 61923 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 106 105 13 127 126
   c=IN IP4 175.101.6.194
   a=rtcp:62270 IN IP4 175.101.6.194
   a=candidate:3707028242 1 udp 2122260223 192.168.137.224 61923 typ host generation 0
   a=candidate:3707028242 2 udp 2122260222 192.168.137.224 63755 typ host generation 0
   a=candidate:2457288674 1 tcp 1518280447 192.168.137.224 57594 typ host tcptype passive generation 0
   a=candidate:2457288674 2 tcp 1518280446 192.168.137.224 57595 typ host tcptype passive generation 0
   a=candidate:3040775379 2 udp 1686052606 175.101.6.194 62270 typ srflx raddr 192.168.137.224 rport 63755 generation 0
   a=candidate:3040775379 1 udp 1686052607 175.101.6.194 61923 typ srflx raddr 192.168.137.224 rport 61923 generation 0
   a=ice-ufrag:qKXXOxJgqONqBvsa
   a=ice-pwd:68AY37H14uz4ZKtm2SVmgUqJ
   a=fingerprint:sha-256 DB:19:12:0B:9E:C6:E6:7D:5D:5A:8E:42:FA:19:01:E6:1B:EE:D3:A4:78:AE:4B:78:B2:64:9D:62:87:08:C6:A0
   a=setup:actpass
   a=mid:audio
   a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
   a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
   a=sendrecv
   a=rtcp-mux
   a=rtpmap:111 opus/48000/2
   a=fmtp:111 minptime=10; useinbandfec=1
   a=rtpmap:103 ISAC/16000
   a=rtpmap:9 G722/8000
   a=rtpmap:102 ILBC/8000
   a=rtpmap:0 PCMU/8000
   a=rtpmap:8 PCMA/8000
   a=rtpmap:106 CN/32000
   a=rtpmap:105 CN/16000
   a=rtpmap:13 CN/8000
   a=rtpmap:127 red/8000
   a=rtpmap:126 telephone-event/8000
   a=maxptime:60
   a=ssrc:195988962 cname:ssPqPmzB2IVbD7OG
   a=ssrc:195988962 msid:ARDAMS ARDAMSa0
   a=ssrc:195988962 mslabel:ARDAMS
   a=ssrc:195988962 label:ARDAMSa0

---

Aug 23 15:30:33  restcomm-olympus[2979] <Notice>: (RCDevice.m:211) [RCDevice unlisten], state: 1
Aug 23 15:30:33  restcomm-olympus[2979] <Error>: (RCDevice.m:249) [RCDevice asyncDeviceDidStopListeningForIncomingConnections], device state: 0 connectivity type: 1
Aug 23 15:30:33  restcomm-olympus[2979] <Debug>: (ssc_sip.mm:2065) un-REGISTER sip:100001@xsip.ccilconnect.com
Aug 23 15:30:33  restcomm-olympus[2979] <Debug>: (ssc_sip.mm:2378) UA: quitting (this can take some time)
send 735 bytes to udp/[104.218.120.106]:5060 at 10:00:33.846467:

---

   REGISTER sip:xsip.ccilconnect.com SIP/2.0
   Via: SIP/2.0/UDP 192.168.137.224:63612;rport;branch=z9hG4bKvZQjF3rr1Q4aj
   Max-Forwards: 70
   From: sip:100001@xsip.ccilconnect.com;tag=y07BmF5442SZD
   To: sip:100001@xsip.ccilconnect.com
   Call-ID: bb610b25-e3ba-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637046 REGISTER
   Contact: sip:175.101.6.194:62234;transport=udp
   Expires: 0
   User-Agent: TelScale Restcomm iOS Client 1.0.0 BETA4
   Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, PRACK, MESSAGE, SUBSCRIBE, NOTIFY, REFER, UPDATE
   Supported: timer, 100rel, path
   Authorization: Digest username="100001", realm="asterisk", nonce="320ec0c4", algorithm=MD5, uri="sip:xsip.ccilconnect.com", response="87caefb9328a28800c3265aed8f88dcb"
   Content-Length: 0

---

send 735 bytes to udp/[104.218.120.106]:5060 at 10:00:33.863052:

---

   REGISTER sip:xsip.ccilconnect.com SIP/2.0
   Via: SIP/2.0/UDP 192.168.137.224:63612;rport;branch=z9hG4bKX8gBHy9Uy0tXD
   Max-Forwards: 70
   From: sip:100001@xsip.ccilconnect.com;tag=U5U1eyjtD8p7a
   To: sip:100001@xsip.ccilconnect.com
   Call-ID: a95264a1-e3ba-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637031 REGISTER
   Contact: sip:175.101.6.194:62234;transport=udp
   Expires: 0
   User-Agent: TelScale Restcomm iOS Client 1.0.0 BETA4
   Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, PRACK, MESSAGE, SUBSCRIBE, NOTIFY, REFER, UPDATE
   Supported: timer, 100rel, path
   Authorization: Digest username="100001", realm="asterisk", nonce="1571c8c8", algorithm=MD5, uri="sip:xsip.ccilconnect.com", response="05884311e00f06ed6d0a8e4e6868ce82"
   Content-Length: 0

---

Aug 23 15:30:33  restcomm-olympus[2979] <Debug>: (ssc_sip.mm:2245) UA: nua_shutdown: 100 Shutdown started
nta_outgoing_tcancel: trying to cancel cancelled request
Aug 23 15:30:33  restcomm-olympus[2979] <Debug>: (ssc_sip.mm:2245) UA: nua_shutdown: 100 Shutdown started
recv 573 bytes from udp/[104.218.120.106]:5060 at 10:00:34.070723:

---

   SIP/2.0 401 Unauthorized
   Via: SIP/2.0/UDP 192.168.137.224:63612;branch=z9hG4bKvZQjF3rr1Q4aj;received=175.101.6.194;rport=62234
   From: sip:100001@xsip.ccilconnect.com;tag=y07BmF5442SZD
   To: sip:100001@xsip.ccilconnect.com;tag=as738173d1
   Call-ID: bb610b25-e3ba-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637046 REGISTER
   Server: FPBX-2.11.0(11.21.0)
   Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
   Supported: replaces, timer
   WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="4cf1d6ef", stale=true
   Content-Length: 0

---

send 735 bytes to udp/[104.218.120.106]:5060 at 10:00:34.075010:

---

   REGISTER sip:xsip.ccilconnect.com SIP/2.0
   Via: SIP/2.0/UDP 192.168.137.224:63612;rport;branch=z9hG4bKyHa4jStZU9ggS
   Max-Forwards: 70
   From: sip:100001@xsip.ccilconnect.com;tag=y07BmF5442SZD
   To: sip:100001@xsip.ccilconnect.com
   Call-ID: bb610b25-e3ba-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637047 REGISTER
   Contact: sip:175.101.6.194:62234;transport=udp
   Expires: 0
   User-Agent: TelScale Restcomm iOS Client 1.0.0 BETA4
   Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, PRACK, MESSAGE, SUBSCRIBE, NOTIFY, REFER, UPDATE
   Supported: timer, 100rel, path
   Authorization: Digest username="100001", realm="asterisk", nonce="4cf1d6ef", algorithm=MD5, uri="sip:xsip.ccilconnect.com", response="91c1e8369a2e6521212e0afbc383e7e3"
   Content-Length: 0

---

recv 561 bytes from udp/[104.218.120.106]:5060 at 10:00:34.080507:

---

   SIP/2.0 401 Unauthorized
   Via: SIP/2.0/UDP 192.168.137.224:63612;branch=z9hG4bKX8gBHy9Uy0tXD;received=175.101.6.194;rport=62234
   From: sip:100001@xsip.ccilconnect.com;tag=U5U1eyjtD8p7a
   To: sip:100001@xsip.ccilconnect.com;tag=as01ef8e59
   Call-ID: a95264a1-e3ba-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637031 REGISTER
   Server: FPBX-2.11.0(11.21.0)
   Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
   Supported: replaces, timer
   WWW-Authenticate: Digest algorithm=MD5, realm="asterisk", nonce="492037c4"
   Content-Length: 0

---

send 735 bytes to udp/[104.218.120.106]:5060 at 10:00:34.084987:

---

   REGISTER sip:xsip.ccilconnect.com SIP/2.0
   Via: SIP/2.0/UDP 192.168.137.224:63612;rport;branch=z9hG4bKZt3vmmB3rj72m
   Max-Forwards: 70
   From: sip:100001@xsip.ccilconnect.com;tag=U5U1eyjtD8p7a
   To: sip:100001@xsip.ccilconnect.com
   Call-ID: a95264a1-e3ba-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637032 REGISTER
   Contact: sip:175.101.6.194:62234;transport=udp
   Expires: 0
   User-Agent: TelScale Restcomm iOS Client 1.0.0 BETA4
   Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, PRACK, MESSAGE, SUBSCRIBE, NOTIFY, REFER, UPDATE
   Supported: timer, 100rel, path
   Authorization: Digest username="100001", realm="asterisk", nonce="492037c4", algorithm=MD5, uri="sip:xsip.ccilconnect.com", response="d0e5d339b8800cc0d3d8c41913a364e6"
   Content-Length: 0

---

recv 524 bytes from udp/[104.218.120.106]:5060 at 10:00:34.242545:

---

   SIP/2.0 200 OK
   Via: SIP/2.0/UDP 192.168.137.224:63612;branch=z9hG4bKyHa4jStZU9ggS;received=175.101.6.194;rport=62234
   From: sip:100001@xsip.ccilconnect.com;tag=y07BmF5442SZD
   To: sip:100001@xsip.ccilconnect.com;tag=as738173d1
   Call-ID: bb610b25-e3ba-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637047 REGISTER
   Server: FPBX-2.11.0(11.21.0)
   Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
   Supported: replaces, timer
   Expires: 0
   Date: Tue, 23 Aug 2016 10:00:34 GMT
   Content-Length: 0

---

recv 524 bytes from udp/[104.218.120.106]:5060 at 10:00:34.254231:

---

   SIP/2.0 200 OK
   Via: SIP/2.0/UDP 192.168.137.224:63612;branch=z9hG4bKZt3vmmB3rj72m;received=175.101.6.194;rport=62234
   From: sip:100001@xsip.ccilconnect.com;tag=U5U1eyjtD8p7a
   To: sip:100001@xsip.ccilconnect.com;tag=as01ef8e59
   Call-ID: a95264a1-e3ba-1234-2dbc-bbb3cb7b8e5f
   CSeq: 95637032 REGISTER
   Server: FPBX-2.11.0(11.21.0)
   Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
   Supported: replaces, timer
   Expires: 0
   Date: Tue, 23 Aug 2016 10:00:34 GMT
   Content-Length: 0

---

nta_outgoing_tcancel: trying to cancel cancelled request
Aug 23 15:30:35  restcomm-olympus[2979] <Debug>: (ssc_sip.mm:2245) UA: nua_shutdown: 101 Shutdown in progress

**Comment by atsakiridis** [comment]
Hi @SURENDRA7700 seems the registration fails, hence you are not able to make a call. Please use correct credentials for your server and retry. Also we have shipped a new [release](https://github.com/RestComm/restcomm-ios-sdk/releases/tag/v1.0.0-beta.4.2) that you can try.

Closing issue for now.
