### ISSUE TITLE
gst/gst.h not found

### ISSUE THREAD

**Issue by gizmoboy7** [RestComm/restcomm-ios-sdk#480]
Hi, 
I'm just starting to fiddle with the restcomm sdk, i've followed the steps given in the prerequisites, but i'm importing the RestCommClient as source and not as a static library. 
I'm getting this error `gst/gst.h not found`
I'm sure i'm missing something, can someone point what it is ? Been breaking my head for a few hours now

**Comment by atsakiridis** [comment]
Hi @gizmoboy7 and sorry for the late reply, must have gone under my radar. Ok, so we have introduced CocoaPods in the Restcomm iOS SDK the last month so you should be able to integrate it much easier. Please refer to our [Quick Start Guide](http://docs.telestax.com/restcomm-client-ios-sdk-quick-start/) for a walkthrough.

Feel free to get back to us if you have any issues
