### ISSUE TITLE
[!] Error installing sofia-sip-library  Cocoa pods

### ISSUE THREAD

**Issue by TheEngineerz** [RestComm/restcomm-ios-sdk#511]
When i am installing pod it give me the following error

here is my podfile

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestRestcom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "restcomm-ios-sdk", :git => 'https://github.com/RestComm/restcomm-ios-sdk.git'
  # Pods for TestRestcom

end
```
```
pod install

Analyzing dependencies
Fetching podspec for `restcomm-ios-sdk` from `../../`
Downloading dependencies
Installing restcomm-ios-sdk (1.0.0-beta.4.2)
Installing sofia-sip-library (1.12.11)

[!] Error installing sofia-sip-library
[!] /usr/bin/curl -f -L -o /var/folders/fb/y1jqqtdn2rs0ds_9d5_209h00000gn/T/d20161123-13613-come2o/file.zip https://github.com/RestComm/restcomm-ios-sdk/releases/download/v1.0.0-beta.4/sofia-sip-library.zip --create-dirs --netrc-optional

  % Total   % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

```

![screen shot 2016-11-23 at 6 45 43 pm](https://cloud.githubusercontent.com/assets/5149947/20564113/71d62708-b1ad-11e6-872b-a7ba3144fa1a.png)

**Comment by atsakiridis** [comment]
Hello, can you try the following:
- Comment out the `use_frameworks!` line
- Replace the pod line with `pod 'restcomm-ios-sdk'` (i.e. remove the git link)

For example:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'your-target' do
  # Pods for your-project
  pod 'restcomm-ios-sdk'

  ...
end
```

**Comment by TheEngineerz** [comment]
Now my Podfile is 

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

```
target 'TestRestcom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod "restcomm-ios-sdk"
  # Pods for TestRestcom
end
```

But it give me this
```

Analyzing dependencies
[!] Unable to find a specification for `restcomm-ios-sdk`

```

I am using xcode 8.1

**Comment by atsakiridis** [comment]
Hmm, strange which CocoaPods version do you have?

**Comment by TheEngineerz** [comment]
@atsakiridis I just create a New project Initialized `Podfile` and run the `pod install`

**Comment by atsakiridis** [comment]
Please let me know the output of:
```
$ pod --version
```

And then update your CocoaPods repo in case its outdated:
```
$ pod repo update
```

**Comment by TheEngineerz** [comment]
```
Mini2:TestRestcom usama$ pod --version
1.1.1
Mini2:TestRestcom usama$ pod repo update
Mini2:TestRestcom usama$ 

```

**Comment by atsakiridis** [comment]
Right, so did you try `pod install` after the update? What are you getting in the console?

**Comment by TheEngineerz** [comment]
Great I did

sudo gem uninstall cocoapods 
and
sudo gem install cocoapods

and its working
Thank you @atsakiridis  for the help but it is strange . previously i had 1.1.1 and the new installed is also 1.1.1 
```
 pod install
Analyzing dependencies
Downloading dependencies
Installing restcomm-ios-sdk (0.9.1)
Installing sofia-sip-library (1.12.11.4)
Installing webrtc-framework (14493.3)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `TestRestcom.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

**Comment by atsakiridis** [comment]
Weird indeed... Glad it worked :)

**Comment by TheEngineerz** [comment]
@atsakiridis May be i should create a new thread for this .

Ok previously i was testing in new xcode project . But now i have included the same in my Podfile of existing project .

`pod "restcomm-ios-sdk"`

 Every thing was installed successfully but when i ran the project it gave me

![screen shot 2016-11-23 at 9 08 13 pm](https://cloud.githubusercontent.com/assets/5149947/20569370/b0ce08b8-b1c1-11e6-9a79-dcabb804a99a.png)

**Comment by TheEngineerz** [comment]
Ok I found that i am using `use_frameworks!` in my Podfile but if i remove it then it does not install pod successfully because i am using some other Swift Pods how i can sort this thing

**Comment by atsakiridis** [comment]
@TheEngineerz let's continue the discussion about that at #512
