### ISSUE TITLE
Webrtc-framework provided in POD has CFBundleSupportedPlatforms issue

### ISSUE THREAD

**Issue by ForGuru** [RestComm/restcomm-ios-sdk#515]
During testing i found that WebRTC framework you provided in PD has serious issues in info.plist
CFBundleSupportedPlatforms = iPhoneSimulator

So will not be accepted by Apple.

I have manually modified it to iPhoneOS to work properly.

**Comment by atsakiridis** [comment]
@ForGuru thanks for reporting, this is generated from Google build scripts, so maybe we used some wrong flag there. Is it working for you after modification?

**Comment by ForGuru** [comment]
@atsakiridis yes I modified the info.plist of framework and it worked. :)

can you share etc script you used to build the framework ?

**Comment by atsakiridis** [comment]
@ForGuru, there's no script to build the framework. I'm using this procedure https://medium.com/@atsakiridis/building-a-fat-webrtc-framework-on-ios-8610fffb2224#.ibztvdb8j

**Comment by atsakiridis** [comment]
Just fixed that in 'webrtc-framework' CocoaPod: version [14493.4](https://cocoapods.org/pods/webrtc-framework). Please try again and let us know if it is ok
