### ISSUE TITLE
Add bug reporting facilities

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-ios-sdk#522]
After discussing with @ivelin and @deruelle about the fact that its hard for not technically savvy people to be able to easily report issues, we decided to improve the clients

One approach is to use the simplistic Android approach where you git a 'bug report' button and a mail is generated and the user can edit the subject to add a simple note. That email has predefined the recepient (project lead, or service) and the subject that also shows the timezone, to be able to correlate.

Another approach is to introduce a new screen that will operate more contextually and also be populated with reasonable defaults. Also that screen could be made to pull the last called number and make it available

Let's brainstorm a bit on that

**Comment by deruelle** [comment]
This should probably be available only for *.restcomm.com domains

**Comment by atsakiridis** [comment]
@deruelle we 've been discussing this with @ipsilantide and this is what we came up with:

- Provide a button for bug report (have already done that for Android) in the Main Screen.
- When the button is pressed the user should be shown a new Dialog or Activity
- The user will be presented with the following input fields:
  - **Issue**: (Drop down with the following options:) 
    - Dropped midway into call
    - Could not make a call (please provide more details below)
    - Call seems connected but no audio/video
    - Could not send Text Message
    - Cannot connect to Restcomm due to time out (Registration issue)
    - Cannot connect to Restcomm due to authentication failure
    - Other (please specify below)
  - **Additional Note**: Optional where the user can add more info, or describe better if the issue above was 'Other'. If issue above was 'Other' we can make this mandatory
  - **Peer number/client**: Here the last peer we talked to will be automatically filled if the issue chosen above is call related. Otherwise it will remain _'N/A for non call issues'_. Will still stay editable for the user to edit if they want.
- Additional, implicitly collected data (not visible to the UI):
  - **Client Name**
  - **Restcomm Domain**
  - **Time & Zone**
  - **Olympus Version**
  - **Logs**
- As discussed this report will only be usable for *.restcomm.com domains
- If the user presses Send, those data will be sent to SDKs lead (and later to a support email)
- Was thinking about automated screenshot, but it's going to be hard to automate that in a manner that will be usable UX wise as we need to have a 'Report Issue' button in all screens and be able to tap on it without messing with the erroneous state. So I think we can instead add a note in the new UI element saying that they can add screenshots as attachments to the email. 

What do you think?

**Comment by deruelle** [comment]
That sounds good for a first iteration. We can refine as people using it provide feedback.

**Comment by atsakiridis** [comment]
Great, thanks @deruelle

**Comment by atsakiridis** [comment]
Consider providing similar functionality with Android (notice though that iOS is much more stringent about integrating with email, etc). Actually review that that functionality actually helped people, cause so far we get very little feedback from that
