### ISSUE TITLE
RestComm with other VoIP Servers

### ISSUE THREAD

**Issue by mvenkatesh431** [RestComm/restcomm-ios-sdk#531]
Hi all,

   I am new to RestComm, I have built one WebRTC application using OpenSIPS/Kamailio and RTPEngine. 
It works fine on web and Android.Now we are now trying to build one iOS Application. 

Is it possible to Use RestComm iOS SDK with Asterisk, Freeswitch, Kamailio or OpenSIPS? 

Thanks

**Comment by deruelle** [comment]
@mvenkatesh431 yes for signalling we use standard SIP which will work with all of them and for Media we use WebRTC standards so as long as those SIP Servers are compatible with DTLS-SRTP, ICE etc which I believe Asterisk and Freeswitch are you should be able to make it work. AFAIK, Kamailio and OpenSIPS don't handle media, only SIP signalling.

**Comment by mvenkatesh431** [comment]
Thanks,  Deruelle
