### ISSUE TITLE
Call Disconnects while Switching from WiFi to Data(3G/4G)

### ISSUE THREAD

**Issue by ForGuru** [RestComm/restcomm-ios-sdk#534]
Active call disconnects when we switch from WiFi to Data (3G/4G) or vice versa. Do you have any idea how to handle this scenario into the sdk to avoid disconnection of the call

**Comment by atsakiridis** [comment]
@ForGuru I'm afraid this is not implemented yet. We have [future plans](https://github.com/RestComm/restcomm-android-sdk/issues/174) for it, but first we need to lay the foundation in Restcomm-Connect. So a tentative plan is for version 2.0.0.

Would you be interested in contributing it when time comes

**Comment by atsakiridis** [comment]
Will be implemented as part of: https://github.com/RestComm/restcomm-ios-sdk/issues/542. Closing this to be consistent with other SDKs.
