### ISSUE TITLE
App is unable to make call after we move away from it

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/restcomm-ios-sdk#541]
if we move from `olympus` to another app and then come back to `olympus`, it is not possible to make any calls. it looks like it is unable to re-establish the connection.
At this point We have to kill the app and then relaunch to make any calls.
Here is a screen shot of what we see when try to make calls.
![ios](https://cloud.githubusercontent.com/assets/17044714/21881193/c5532654-d8c4-11e6-9f51-bc906c707318.jpg)

**Comment by atsakiridis** [comment]
Removed enhancement and added important tag, as this messing with the state will bite everybody at some point
