### ISSUE TITLE
Update local notifications UI for Olympus application for iOS versions < 10.0

### ISSUE THREAD

**Issue by ognjenns** [RestComm/restcomm-ios-sdk#631]
We need to update local notifications:
1. Add buttons 'Accept' and 'Decline'. 
-When user taps on accept, Olympus app should be opened and we should see call dialog
-When user taps on cancel, notification will be dismissed and removed from notification list

2. Add ringing sound for call notification
- We will need to add new sound for the ringing (linear PCM or IMA4, <30sec). When user taps on the notification (answer/decline) or dismissing it should stop playing

3. If user does not answer the call or dismiss the notification. We should remove the call notification with missed call notification

**Comment by atsakiridis** [comment]
This is no longer applicable as we 're dropping iOS 9.0 support
