### ISSUE TITLE
Create settings screen push configuration

### ISSUE THREAD

**Issue by ognjenns** [RestComm/restcomm-ios-sdk#636]
We need a new screen on Olympus application where push notification parameters can be set.
Some of the settings should be predefined.

**Comment by atsakiridis** [comment]
@ognjenns let's follow the same logic Mosa followed for Android Olympus Settings. You can find a screenshot [here](https://docs.google.com/document/d/1GA6DgwcTq4RP0MSjkyn4yQhuZos3qZvWiNYz1ErBY0k/edit#heading=h.s8ymoqp00ly0)

If you see that there are differences between iOS and Android on that respect we can discuss further. But the idea is to make everything (that makes sense) configurable in the App level
