### ISSUE TITLE
Document the flows for callkit/pushkit flows

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/restcomm-ios-sdk#638]
So that we know how we implemented that for when we need to revisit in the future, otherwise we 'll get lost. 

Let's use [Plant UML](http://plantuml.com/plantuml/form) sequence diagrams for that. You can use [this](https://telestax.slack.com/files/U0452JH39/F7DEWLN6A/image_uploaded_from_ios.jpg) as a base and add more to it as you see fit. Let's also include design decisions like the fact that the server side doesn't provide any payload in the Push Notification messages and how it all works. 

Similarly for push text messages

Let's also add a section is the design doc about these extra settings that we need to be mindful of. Like having the client support push (using http PUT), using this sandbox when testing using developer certificate and anything else you see needs more clarification. That way when we come back to this codebase we are able to figure things out

Lets put those resources inside our already existing design doc for push notifications of iOS.

**Comment by ognjenns** [comment]
We need to add some information we find out investigating backgrounding stuff
