### ISSUE TITLE
Investigation about background mode limits

### ISSUE THREAD

**Issue by ognjenns** [RestComm/restcomm-ios-sdk#650]
We need to investigate all limitations of the background mode when push is received with pushkit.

**Comment by ognjenns** [comment]
After investigation of the pushkit. I got to conclusion that the iOS is 'wake' an app, after receiving voip push, for some period of time.

I couldn't find the official timeframe on apple documentation; I have checked Apple's wwdc:
https://developer.apple.com/videos/play/wwdc2017/238/?time=1136
_Here, we can see I'm not calling the completion handler in this case when I receive my incoming push. I'm just doing some processing and then I'm letting the device just go to sleep after a fixed period of time._ 

also, while investigating I've found interesting question/investigation which is never answered:
https://forums.developer.apple.com/thread/28019

**Comment by atsakiridis** [comment]
@ognjenns we still need to find a way to make sense of it or we won't to be able to design a proper solution. If the docs aren't good enough have you tried to test it and find out what is going on under the hood? I think we already discussed on checking the App lifecycle changes and coming up with the answer ourselves.

**Comment by ognjenns** [comment]
After testing conclusion is this:
- If application is terminated, push will 'wake' the app and connect to rc device. After ~30 seconds, application will be moved to suspended mode (it will not clear any objects if it doesnt have to);
from documentation: (The app is in memory but is not executing code. The system suspends apps that are in the background and do not have any pending tasks to complete. The system may purge suspended apps at any time without waking them up to make room for other apps.).
Test results:

1. 
Nov  7 09:52:54 Manevski-Ognjens-iPhone restcomm-olympus[4470] <Notice>: AppDelegate ---pushReceived
Nov  7 09:52:54 Manevski-Ognjens-iPhone restcomm-olympus[4470] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 09:53:24 Manevski-Ognjens-iPhone assertiond[66] <Notice>: [restcomm-olympu:4470] suspend success


2.
Nov  7 10:10:00 Manevski-Ognjens-iPhone restcomm-olympus[4519] <Notice>: AppDelegate ---pushReceived
Nov  7 10:10:30 Manevski-Ognjens-iPhone assertiond[66] <Notice>: [restcomm-olympu:4519] suspend success


3.
Nov  7 10:16:45 Manevski-Ognjens-iPhone restcomm-olympus[4527] <Notice>: AppDelegate ---pushReceived
Nov  7 10:17:16 Manevski-Ognjens-iPhone assertiond[66] <Notice>: [restcomm-olympu:4527] suspend success

4.
Nov  7 10:23:06 Manevski-Ognjens-iPhone restcomm-olympus[4532] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 10:23:20 Manevski-Ognjens-iPhone restcomm-olympus[4532] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 10:23:44 Manevski-Ognjens-iPhone restcomm-olympus[4532] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 10:23:59 Manevski-Ognjens-iPhone restcomm-olympus[4532] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 10:24:19 Manevski-Ognjens-iPhone restcomm-olympus[4532] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 10:24:51 Manevski-Ognjens-iPhone restcomm-olympus[4532] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 10:25:24 Manevski-Ognjens-iPhone assertiond[66] <Notice>: [restcomm-olympu:4532] suspend success

5.
Nov  7 10:33:36 Manevski-Ognjens-iPhone restcomm-olympus[4542] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 10:34:07 Manevski-Ognjens-iPhone assertiond[66] <Notice>: [restcomm-olympu:4542] suspend success
Nov  7 10:34:45 Manevski-Ognjens-iPhone restcomm-olympus[4542] <Notice>: OGGIE: ===== didReceiveIncomingPushWithPayload (when in background) ++++>>>>>>+++++>>>>
Nov  7 10:35:18 Manevski-Ognjens-iPhone assertiond[66] <Notice>: [restcomm-olympu:4542] suspend success
